global:
  scrape_interval: '5s'
  evaluation_interval: '5s'

# A scrape configuration containing exactly one endpoint to scrape:
# Replace HOSTIP below with docker host IP
scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kafka-consumer'
    # will give application metrics
    metrics_path: /metrics
    static_configs:
      - targets: ['HOST_IP:3001']